// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzihlgsdtqusujbrmbas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6aWhsZ3NkdHF1c3VqYnJtYmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDI3MDIsImV4cCI6MjA1OTcxODcwMn0.Siue0fXKGUgGVnkAHFWeVA51FnXVHqyvm-I0ThkScgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);